FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY . .
RUN apk add --no-cache git make
RUN make install
RUN make build-linux

FROM alpine:3.19.0
WORKDIR /app
COPY --from=builder /app/bin/linux/server ./server
RUN echo -e 'server:\n  port: 8080' > ./config.yaml
RUN chmod +x server

ENV PORT=8080
CMD ["sh", "-c", "./server --port ${PORT}"]